name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake flex bison graphviz

    - name: Install Doxygen 1.13.2 from tarball
      run: |
        wget https://www.doxygen.nl/files/doxygen-1.13.2.linux.bin.tar.gz
        tar -xzf doxygen-1.13.2.linux.bin.tar.gz
        cd doxygen-1.13.2
        sudo make install

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_WPAT }}
        publish_dir: ./docs
